language: java
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
after_success:
- mvn -P coverall clean test jacoco:report coveralls:report
notifications:
  slack:
    secure: q7BLomWpY7hvay1W8AaCsHlmPNabBBI5pB/d0WFhtohRdVzNapLI7eTkiryWi5noOS27wSJqa6Hw95vMP0hCNJipZIFel8anCu9wR+zjFpkUO1p3X6k2IE/plDyYo1ZYWm1oWlBWnBOkz8+DTEM1zW3/qJxV2PtUdNrEXc3lCXMpx6kq6ve5VGFLn2X8HvZ1668wqtqmWIHc6rRgrcDD3jSwlsMuRAzyLnZZiNQvi+N0dNk9ClZoHHuXRx+10gdYrgx1g7eYfTko/20t9M1r2zxoZsh1fWR5P0Das7UtCP3G/nieGCAPmFJeoUzs3lIXXmIaPCka0KLqILuqGW4hb+dN8aqnsOdhGneTEHcD5IFbopTatGuQEkOaY5e38CaA0bMtpmSlzwDaE10DWj6xZSkgtDC1kmGMky5gNl8qF8Wiiz0V9WZvMpJsJkZ9TgEp49gAurzuf0r8K0NwefvAPnW/07/sqYhlb03xhG3OdetoAaTPAOAqBtOO9pZpsZBVMfTjwDCPR4CI0fhbbvC8xrk0EDFnjk8boaPiu/YFmJuALNd6dyPlDZFao+462HDlr96www3DjHDVsMZXYihRWzL7/1b4113sszryOG+Xm9fIy+JfeBx5OjtYXt1V9sy7erQlFSxJ1TjQs2QIKlYljmk7qRufFiIMjgYKtHdw+HU=
